desc = "Support for creating packed tables of strings and save/load simple tables with values"
keywords = ["Strings"]
license = "MIT"
name = "StrBase"
deps = ["Dates", "Pkg", "Test"]
git-tree-sha1 = "9c5a49b47a917e6c35dff90971f4326c37f78be6"
uuid = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"
version = "0.2.1"
repo = "https://github.com/JuliaString/StrBase.jl.git"
